[package]
name = "kernel"
version = "0.1.0"
authors = ["KernelFreeze <kernelfreeze@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = { git = "https://github.com/rust-osdev/bootloader", branch = "uefi" }
volatile = { version = "0.4.3", features = ["unstable"] }
font8x8 = { version = "0.2.7", default-features = false, features = ["unicode"] }
spin = { version = "0.7.1", features = ["ticket_mutex"] }
futures = { version = "0.3", default-features = false }
buddy_system_allocator = "0.6.0"
bitflags = "1.2.1"
core_detect = "0.1.0"
bare-io = { version = "0.2", default-features = false, features = ["alloc", "nightly"] }
log = { version = "0.4.14", default-features = false }
anyhow = { version = "1.0", default-features = false }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { version = "0.13.1" }

[package.metadata.bootloader]
map-physical-memory = true

[dependencies.crossbeam-queue]
version = "0.3.1"
default-features = false
features = ["alloc"]

[dependencies.smallvec]
version = "1.6.1"
default-features = false
features = ["union", "const_generics", "specialization", "may_dangle"]

[dependencies.wain-exec]
git = "https://github.com/etheryal/wain"
branch = "main"
default-features = false
features = ["core"]

[dependencies.wain-validate]
git = "https://github.com/etheryal/wain"
branch = "main"
default-features = false
features = ["core"]

[dependencies.wain-syntax-binary]
git = "https://github.com/etheryal/wain"
branch = "main"
default-features = false
features = ["core"]

[dependencies.wain-syntax-text]
git = "https://github.com/etheryal/wain"
branch = "main"
default-features = false
features = ["core"]

[dependencies.wain-ast]
git = "https://github.com/etheryal/wain"
branch = "main"
default-features = false
features = ["core"]
