[package]
name = "etheryal-kernel"
version = "0.1.0"
authors = ["KernelFreeze <kernelfreeze@outlook.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["bin"]

[build-dependencies]
built = { version = "0.4", features = ["git2"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = { git = "https://github.com/rust-osdev/bootloader", branch = "uefi" }
volatile = { version = "0.4", features = ["unstable"] }
font8x8 = { version = "0.2", default-features = false, features = ["unicode"] }
spin = { version = "0.7", features = ["ticket_mutex"] }
futures = { version = "0.3", default-features = false }
buddy_system_allocator = "0.6"
bitflags = "1.2"
core_detect = "0.1"
log = { version = "0.4", default-features = false }
libm = "0.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { version = "0.13" }

[package.metadata.bootloader]
map-physical-memory = true

[dependencies.crossbeam-queue]
version = "0.3"
default-features = false
features = ["alloc"]

[dependencies.smallvec]
version = "1.6"
default-features = false
features = ["union", "const_generics", "specialization", "may_dangle"]

[dependencies.wasmi]
git = "https://github.com/etheryal/wasmi"
default-features = false
features = ["core"]
