[package]
name = "kernel"
version = "0.1.0"
authors = ["KernelFreeze <kernelfreeze@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = { git = "https://github.com/rust-osdev/bootloader", branch = "uefi" }
volatile = { version = "0.4.3", features = ["unstable"] }
font8x8 = { version = "0.2.7", default-features = false, features = ["unicode"] }
lazy_static = { version = "*", features = ["spin_no_std"] }
spin = "0.7.1"
slabmalloc = { git = "https://github.com/gz/rust-slabmalloc" }
futures = { version = "0.3", default-features = false }
buddy_system_allocator = "0.6.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { version = "0.13.1" }
apic = { git = "https://github.com/rust-osdev/apic" }

[package.metadata.bootloader]
map-physical-memory = true

[dependencies.crossbeam-queue]
version = "0.3.1"
default-features = false
features = ["alloc"]
