[env]
RUST_COMPILER_RT_ROOT = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/libs/compiler-rt"

[tasks.download-compiler-rt]
install_script = '''
if [ ! -d "libs/compiler-rt/" ] 
then
    echo "Downloading LLVM's compiler RT."
    mkdir -p libs/compiler-rt/
    cd libs/compiler-rt/
    curl -L https://github.com/llvm/llvm-project/tarball/llvmorg-11.0.1 | tar xz --wildcards "*/compiler-rt/*" --strip-components=2
fi
'''

[tasks.install-llvm-tools-preview]
install_crate = { rustup_component_name = "llvm-tools-preview" }

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.install-clippy]
install_crate = { rustup_component_name = "clippy" }

[tasks.clippy]
description = "Runs clippy checks."
category = "Build"
command = "cargo"
args = [
    "clippy",
    "--color",
    "always",
    "--all-targets",
    "--all-features",
    "--",
    "-D",
    "warnings",
]
dependencies = [
    "download-compiler-rt",
    "install-llvm-tools-preview",
    "install-rust-src",
    "install-clippy",
]

[tasks.format-check]
install_crate = { rustup_component_name = "rustfmt-preview", binary = "rustfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt", "--", "--color", "always", "--check"]

[tasks.build]
dependencies = [
    "download-compiler-rt",
    "install-llvm-tools-preview",
    "install-rust-src",
]

[tasks.test]
dependencies = [
    "download-compiler-rt",
    "install-llvm-tools-preview",
    "install-rust-src",
]

[tasks.dev-test-flow]
dependencies = ["format", "clippy", "test"]

[tasks.build-flow]
dependencies = ["format", "build"]

[tasks.run]
description = "Runs etheryal in a virtual machine."
category = "Build"
command = "cargo"
args = ["run"]
dependencies = [
    "download-compiler-rt",
    "install-llvm-tools-preview",
    "install-rust-src",
]
