[tasks.install-llvm-tools-preview]
install_crate = { rustup_component_name = "llvm-tools-preview" }

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.install-etheryal-bootimage]
install_crate = { crate_name = "etheryal-bootimage", binary = "etheryal-bootimage", test_arg = ["--help"] }

[tasks.install-clippy]
install_crate = { rustup_component_name = "clippy" }

[tasks.clippy]
description = "Runs clippy checks."
category = "Build"
command = "cargo"
args = [
    "clippy",
    "--color",
    "always",
    "--all-targets",
    "--all-features",
    "--",
    "-D",
    "warnings",
]
dependencies = [
    "install-llvm-tools-preview",
    "install-rust-src",
    "install-clippy",
]

[tasks.format-check]
install_crate = { rustup_component_name = "rustfmt-preview", binary = "rustfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt", "--", "--color", "always", "--check"]

[tasks.build]
dependencies = ["install-llvm-tools-preview", "install-rust-src"]

[tasks.test]
dependencies = [
    "install-llvm-tools-preview",
    "install-rust-src",
    "install-etheryal-bootimage",
]

[tasks.run]
description = "Runs etheryal in a virtual machine."
category = "Build"
command = "cargo"
args = ["run"]
dependencies = [
    "install-llvm-tools-preview",
    "install-rust-src",
    "install-etheryal-bootimage",
]

[tasks.dev-test-flow]
dependencies = ["format", "clippy", "test"]

[tasks.build-flow]
dependencies = ["format", "build"]
