[tasks.install-llvm-tools-preview]
install_crate = { rustup_component_name = "llvm-tools-preview" }

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.b]
alias = "build"

[tasks.t]
alias = "test"

[tasks.build]
description = "Runs the rust compiler."
category = "Build"
command = "cargo"
args = ["build"]
dependencies = ["install-llvm-tools-preview", "install-rust-src"]

[tasks.dev-test-flow]
dependencies = ["format", "clippy"]