brace_style = "PreferSameLine"
wrap_comments = true
condense_wildcard_suffixes = true
edition = "2018"
fn_args_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
license_template_path = "docs/LICENSE_TEMPLATE.txt"
match_block_trailing_comma = true
max_width = 130
merge_imports = true
# imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true