name: 'Coverage report'

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  linter:
    name: Submit coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          rustup set profile minimal
          rustup toolchain update nightly --no-self-update
          rustup default nightly
          rustup component add rust-src
          rustup component add llvm-tools-preview
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
          rustup show
          cargo --version
      - name: Generate Coverage Report
        run: |
          export CARGO_INCREMENTAL=0
          export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
          export RUSTDOCFLAGS="-Cpanic=abort"
          cargo build --verbose $CARGO_OPTIONS
          cargo test --verbose $CARGO_OPTIONS
          zip -0 ccov.zip `find . \( -name "YOUR_PROJECT_NAME*.gc*" \) -print`;
          ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: lcov.info
          verbose: true
