name: 'Unit and Integration Tests'

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  linter:
    name: Check Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          rustup set profile minimal
          rustup toolchain update nightly --no-self-update
          rustup default nightly
          rustup component add clippy
          cargo install --force cargo-make
          rustup show
          cargo --version
          cargo make --version
          cargo clippy --version
      - run: cargo make clippy
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          rustup set profile minimal
          rustup toolchain update nightly --no-self-update
          rustup default nightly
          cargo install --force cargo-make
          rustup show
          cargo --version
          cargo make --version
      - name: Install QEMU
        run: |
          sudo apt update
          sudo apt install qemu-system-x86
      - name: Run Tests
        run: |
          cargo make test --verbose
